#!/usr/bin/env node
// scripts/generate-tokens.css.mjs
//
// Build-time generator: reads DARK_TOKENS from @tmbk/canshift-core and emits
// src/styles/tokens.generated.css as the canonical :root { --x: ... } block
// consumed by tailwind.config.ts via hsl(var(--x) / <alpha-value>).
//
// Source of truth: canshift-core/src/design-tokens.ts (Phase 0 of issue #526).
// Run automatically via the `tokens:gen` npm script (hooked into predev/prebuild).

import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

/** @type {string} */
const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
/** @type {string} */
const STUDIO_ROOT = resolve(SCRIPT_DIR, '..')
/** @type {string} */
const CORE_PKG_DIR = resolve(STUDIO_ROOT, 'node_modules', '@tmbk', 'canshift-core')
/** @type {string} */
const CORE_TOKENS_JS = resolve(CORE_PKG_DIR, 'dist', 'design-tokens.js')
/** @type {string} */
const OUTPUT_PATH = resolve(STUDIO_ROOT, 'src', 'styles', 'tokens.generated.css')

const HEADER = [
  '/* AUTO-GENERATED by scripts/generate-tokens.css.mjs — DO NOT EDIT BY HAND */',
  '/* Source of truth: canshift-core/src/design-tokens.ts (DARK_TOKENS) */',
  '',
].join('\n')

/**
 * Build the CSS payload (header + :root block) for a set of CSS variables.
 * @param {Record<string, string>} cssVars
 * @returns {string}
 */
function buildCss(cssVars) {
  const lines = [':root {']
  for (const [name, value] of Object.entries(cssVars)) {
    lines.push(`  ${name}: ${value};`)
  }
  lines.push('}', '')
  return `${HEADER}\n${lines.join('\n')}`
}

/**
 * Write the generated CSS to disk, but skip the write if the file already has
 * identical content. Keeps mtime stable for downstream tools that watch files.
 * @param {string} path
 * @param {string} content
 * @returns {boolean} true if the file was written, false if skipped.
 */
function writeIfChanged(path, content) {
  if (existsSync(path)) {
    const previous = readFileSync(path, 'utf8')
    if (previous === content) {
      return false
    }
  }
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content, 'utf8')
  return true
}

async function main() {
  if (!existsSync(CORE_TOKENS_JS)) {
    throw new Error(
      `canshift-core build artifact not found at ${CORE_TOKENS_JS}. ` +
        `Run \`npm --prefix ../canshift-core run build\` first (predev/prebuild does this automatically).`
    )
  }

  /** @type {{ DARK_TOKENS: import('@tmbk/canshift-core').DesignTokens, tokensToCssVars: (t: import('@tmbk/canshift-core').DesignTokens) => Record<string, string> }} */
  const { DARK_TOKENS, tokensToCssVars } = await import(pathToFileURL(CORE_TOKENS_JS).href)
  const cssVars = tokensToCssVars(DARK_TOKENS)
  const css = buildCss(cssVars)

  const changed = writeIfChanged(OUTPUT_PATH, css)
  const rel = OUTPUT_PATH.replace(`${STUDIO_ROOT}/`, '')
  if (changed) {
    console.log(`[tokens:gen] wrote ${rel} (${Object.keys(cssVars).length} vars)`)
  } else {
    console.log(`[tokens:gen] up to date — ${rel}`)
  }
}

try {
  await main()
} catch (err) {
  const message = err instanceof Error ? err.message : String(err)
  console.error(`[tokens:gen] error: ${message}`)
  process.exit(1)
}
