// DiagnosticsPanel.tsx — Live signal monitor overlay.
// Rendered inside the 320×240 canvas widget area, on top of the dashboard.
// In simulation mode: values are generated by useLiveSignals (oscillating).
// When connected to a device: values come from USB telemetry (firmware pushes every ~200ms).

import { useLiveSignals } from '../../hooks/useLiveSignals'
import { useSignalStore } from '../../stores/signal.store'
import { useDeviceStore } from '../../stores/device.store'

interface DiagnosticsPanelProps {
  scale: number
}

export default function DiagnosticsPanel({ scale }: DiagnosticsPanelProps) {
  const signals = useSignalStore((s) => s.signals)
  const connected = useDeviceStore((s) => s.connected)
  const simulationMode = useDeviceStore((s) => s.simulationMode)
  const values = useLiveSignals()
  const isLive = connected && !simulationMode

  const fs = Math.round(scale * 5.5)
  const pad = Math.round(scale * 6)
  const rowPad = Math.round(scale * 3)
  const barW = Math.round(scale * 32)
  const barH = Math.round(scale * 4)

  return (
    <div
      style={{
        position: 'absolute',
        inset: 0,
        background: '#0D0D0D',
        zIndex: 100,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
      }}
    >
      {/* Header */}
      <div
        style={{
          padding: `${String(pad)}px ${String(pad)}px ${String(Math.round(scale * 3))}px`,
          borderBottom: '1px solid #2A2A2A',
          flexShrink: 0,
          display: 'flex',
          alignItems: 'baseline',
          gap: Math.round(scale * 4),
        }}
      >
        <span
          style={{
            fontSize: fs + 2,
            color: '#FFFFFF',
            fontWeight: 600,
            letterSpacing: '0.08em',
            textTransform: 'uppercase',
          }}
        >
          Diagnostics
        </span>
        {/* Source badge */}
        <span
          style={{
            fontSize: fs - 1,
            color: isLive ? '#33CC55' : simulationMode ? '#FF8800' : '#555555',
            fontWeight: 600,
            letterSpacing: '0.06em',
          }}
        >
          {isLive ? 'LIVE' : simulationMode ? 'SIM' : 'NO DATA'}
        </span>
        <span style={{ fontSize: fs - 1, color: '#444444', marginLeft: 'auto' }}>
          swipe ↓ to close
        </span>
      </div>

      {/* Signal list */}
      <div style={{ overflowY: 'auto', flex: 1 }}>
        {signals.length === 0 ? (
          <div
            style={{
              padding: pad,
              fontSize: fs,
              color: '#888888',
              textAlign: 'center',
              paddingTop: pad * 3,
            }}
          >
            No signals configured.
          </div>
        ) : (
          signals.map((sig) => {
            const raw = values[sig.name]
            const range = sig.max - sig.min || 1
            const pct = raw !== undefined ? Math.max(0, Math.min(1, (raw - sig.min) / range)) : null
            const isDanger = pct !== null && pct >= 0.95
            const isWarn = pct !== null && !isDanger && pct >= 0.8
            const valueColor = isDanger ? '#FF4444' : isWarn ? '#FF8800' : '#CCCCCC'
            const barColor = isDanger ? '#FF444488' : isWarn ? '#FF880088' : '#33CC5555'
            const valueStr = raw !== undefined ? raw.toFixed(1) : '—'

            return (
              <div
                key={sig.name}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  padding: `${String(rowPad)}px ${String(pad)}px`,
                  borderBottom: '1px solid #181818',
                  gap: Math.round(scale * 3),
                }}
              >
                {/* Signal name */}
                <span
                  style={{
                    fontSize: fs,
                    color: '#AAAAAA',
                    flex: 1,
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    whiteSpace: 'nowrap',
                  }}
                >
                  {sig.name.replace(/_/g, ' ')}
                </span>

                {/* Mini bar */}
                <div
                  style={{
                    width: barW,
                    height: barH,
                    background: '#1E1E1E',
                    borderRadius: 2,
                    flexShrink: 0,
                    overflow: 'hidden',
                  }}
                >
                  {pct !== null && (
                    <div
                      style={{
                        width: `${String(Math.round(pct * 100))}%`,
                        height: '100%',
                        background: barColor,
                        borderRadius: 2,
                        transition: 'width 0.25s linear',
                      }}
                    />
                  )}
                </div>

                {/* Value */}
                <span
                  style={{
                    fontSize: fs,
                    color: valueColor,
                    fontVariantNumeric: 'tabular-nums',
                    minWidth: Math.round(scale * 18),
                    textAlign: 'right',
                    flexShrink: 0,
                  }}
                >
                  {valueStr}
                </span>

                {/* Unit */}
                <span
                  style={{
                    fontSize: fs - 1,
                    color: '#555555',
                    minWidth: Math.round(scale * 10),
                    flexShrink: 0,
                  }}
                >
                  {sig.unit}
                </span>
              </div>
            )
          })
        )}
      </div>
    </div>
  )
}
